package backends

import (
	"fmt"
	"sort"
	"strings"

	"github.com/Grizak/cppmake/internal/plan"
)

type NinjaBackend struct{}

func (b *NinjaBackend) Emit(p *plan.Plan) ([]byte, error) {
	var sb strings.Builder

	sb.WriteString("# Generated by cppmake - DO NOT EDIT\n")
	sb.WriteString(fmt.Sprintf("# Project: %s %s\n\n", p.Name, p.Version))

	for _, r := range p.Rules {
		fmt.Fprintf(&sb, "rule %s\n  command = %s\n", r.Name, r.Command)
		if r.Depfile != "" {
			fmt.Fprintf(&sb, "  depfile = %s\n  deps = %s\n", r.Depfile, r.Deps)
		}
		sb.WriteString("\n")
	}

	for _, t := range p.Targets {
		for _, e := range t.Edges {
			fmt.Fprintf(&sb, "build %s: %s %s", join(e.Outputs), e.Rule, join(e.Inputs))
			if len(e.ImplicitInputs) > 0 {
				fmt.Fprintf(&sb, " | %s", join(e.ImplicitInputs))
			}
			if len(e.OrderOnlyInputs) > 0 {
				fmt.Fprintf(&sb, " || %s", join(e.OrderOnlyInputs))
			}
			sb.WriteString("\n")
			for k, v := range sortedVars(e.Vars) {
				fmt.Fprintf(&sb, "  %s = %s\n", k, v)
			}
		}
	}

	fmt.Fprintf(&sb, "\ndefault %s\n", join(p.Defaults))
	return []byte(sb.String()), nil
}

func (b *NinjaBackend) Filename() string {
	return "build.ninja"
}

func join(items []string) string {
	return strings.Join(items, " ")
}

func sortedVars(vars map[string]string) map[string]string {
	keys := make([]string, 0, len(vars))
	for k := range vars {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	sorted := make(map[string]string, len(vars))
	for _, k := range keys {
		sorted[k] = vars[k]
	}
	return sorted
}
