package backends

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"github.com/Grizak/cppmake/internal/parser"
)

type NinjaBackend struct{}

func (b *NinjaBackend) Generate(cfg parser.Config) []byte {
	var sb strings.Builder

	sb.WriteString("# Generated by cppmake - DO NOT EDIT\n")
	fmt.Fprintf(&sb, "# Project: %s %s\n\n", cfg.Project.Name, cfg.Project.Version)

	// 1. Define rules per toolchain
	languages := make([]string, 0, len(cfg.Toolchains))
	for lang := range cfg.Toolchains {
		languages = append(languages, lang)
	}
	sort.Strings(languages)

	for _, lang := range languages {
		tools := cfg.Toolchains[lang]
		toolchainNames := make([]string, 0, len(tools))
		for name := range tools {
			toolchainNames = append(toolchainNames, name)
		}
		sort.Strings(toolchainNames)

		for _, name := range toolchainNames {
			tc := tools[name]
			ruleName := fmt.Sprintf("%s_%s", lang, name)
			fmt.Fprintf(&sb, "rule %s\n", ruleName)

			if tc.Direct {
				// go build -o $out $in
				flags := strings.Join(tc.Flags, " ")
				fmt.Fprintf(&sb, " command = %s %s -o $out $in\n", tc.Run, flags)
			} else {
				// gcc -c $in -o $out
				flags := strings.Join(tc.Flags, " ")
				fmt.Fprintf(&sb, " command = mkdir -p $$(dirname $out) && %s %s -c $in -o $out\n", tc.Run, flags)
			}
			sb.WriteString("\n")
		}
	}

	// 2. Define link-rules
	linkerNames := make([]string, 0, len(cfg.Linkers))
	for name := range cfg.Linkers {
		linkerNames = append(linkerNames, name)
	}
	sort.Strings(linkerNames)

	for _, name := range linkerNames {
		linker := cfg.Linkers[name]
		fmt.Fprintf(&sb, "rule link_%s\n", name)

		// check if Run already contains $out/$in
		if strings.Contains(linker.Run, "$out") {
			fmt.Fprintf(&sb, "  command = mkdir -p $$(dirname $out) && %s %s\n", linker.Run, strings.Join(linker.Flags, " "))
		} else {
			// default for gcc/clang
			fmt.Fprintf(&sb, "  command = mkdir -p $$(dirname $out) && %s %s $in -o $out\n", linker.Run, strings.Join(linker.Flags, " "))
		}
		sb.WriteString("\n")
	}

	seenObjs := make(map[string]bool)
	var allBuildLines []string

	// 3. Build targets
	for _, t := range cfg.Targets {
		out := t.Outfile

		tc := cfg.Toolchains[t.Lang][t.Toolchain]

		if tc.Direct {
			// go, rust - direct
			srcs := strings.Join(t.Src, " ")
			ruleName := fmt.Sprintf("%s_%s", t.Lang, t.Toolchain)
			fmt.Fprintf(&sb, "build %s: %s %s\n", out, ruleName, srcs)
		} else {
			var objs []string
			for _, src := range t.Src {
				obj := filepath.Join("build", "obj", strings.TrimSuffix(src, filepath.Ext(src))+".o")
				objs = append(objs, obj)

				if !seenObjs[obj] {
					ruleName := fmt.Sprintf("%s_%s", t.Lang, t.Toolchain)
					fmt.Fprintf(&sb, "build %s: %s %s\n", obj, ruleName, src)
					seenObjs[obj] = true
				}
			}
			linkRule := fmt.Sprintf("link_%s", t.Linker)
			allBuildLines = append(allBuildLines, fmt.Sprintf("build %s: %s %s\n", out, linkRule, strings.Join(objs, " ")))
		}
		sb.WriteString("\n")
	}

	for _, line := range allBuildLines {
		sb.WriteString(line)
	}

	return []byte(sb.String())
}

func (b *NinjaBackend) Filename() string {
	return "build.ninja"
}
